language: csharp
sudo: required
mono: none
dotnet: 1.0.1
dist: trusty

branches:
  except:
    - 1.0
    - 2.0
    - 2.1
    - dse_3.1

script:
  - dotnet restore src
  - dotnet build src/Cassandra.csproj -c Release -f netstandard1.5
  - dotnet build src/Cassandra.Tests/Cassandra.Tests.csproj -c Release -f netcoreapp1.0
  - dotnet test src/Cassandra.Tests/Cassandra.Tests.csproj -c Release -f netcoreapp1.0
