language: csharp
mono: none
dotnet: 1.0.2
dist: trusty

branches:
  except:
    - 1.0
    - 2.0
    - 2.1
    - dse_3.1

script:
  - dotnet restore src
  - dotnet test src/Cassandra.Tests -c Release -f netcoreapp1.0
