version: "{branch}-{build}"
skip_tags: true
shallow_clone: true
cache:
  - C:\ProgramData\chocolatey\bin -> .\build\appveyor_install.ps1                                                                             
  - C:\ProgramData\chocolatey\lib -> .\build\appveyor_install.ps1
  - C:\Users\appveyor\.ccm\repository -> .\build\appveyor_install.ps1
  - C:\Users\appveyor\deps -> .\build\appveyor_install.ps1
image: Visual Studio 2017
environment:
  NUNIT_PATH: nunit3-console
  matrix:
    - TARGET: net452
      CI_TYPE: UNIT
    - TARGET: netcoreapp1.0
      CI_TYPE: UNIT
    - TARGET: net452
      CASSANDRA_VERSION: 3.10
      CI_TYPE: INTEGRATION
    - TARGET: netcoreapp1.0
      CASSANDRA_VERSION: 3.10
      CI_TYPE: INTEGRATION
    - TARGET: net452
      CASSANDRA_VERSION: 2.2.7
      CI_TYPE: INTEGRATION
    - TARGET: net452
      CASSANDRA_VERSION: 3.10
      CI_TYPE: MEMORY

install:
  - ps: .\build\appveyor_install.ps1
  - ps: .\build\scassandra_install.ps1

before_build:
  - ps: dotnet restore src
  
build_script:
  - ps: >-
      If ("$($env:CI_TYPE)" -eq "UNIT") {
        dotnet build src\Cassandra.Tests\Cassandra.Tests.csproj -c Release -f $env:TARGET
      }
      If ("$($env:CI_TYPE)" -eq "INTEGRATION") {
        dotnet build src\Cassandra.IntegrationTests\Cassandra.IntegrationTests.csproj -c Release -f $env:TARGET
      }

test_script:
  - ps: >-
      If ("$($env:CI_TYPE)" -eq "UNIT") {
        dotnet build src\Cassandra.Tests\Cassandra.Tests.csproj -c Release -f $env:TARGET
        dotnet test src\Cassandra.Tests\Cassandra.Tests.csproj -c Release -f $env:TARGET
      }
      If ("$($env:CI_TYPE)" -eq "INTEGRATION") {
        dotnet build src\Cassandra.IntegrationTests\Cassandra.IntegrationTests.csproj -c Release -f $env:TARGET
        dotnet test src\Cassandra.IntegrationTests\Cassandra.IntegrationTests.csproj -c Release -f $env:TARGET --filter "TestCategory~short"
      }
      If ("$($env:CI_TYPE)" -eq "MEMORY") {
        .\build\memory_tests.ps1
      }

on_failure:
  - ps: >-
      Write-Host "Build failed"
